_BASE_: "../Base-RCNN-DilatedC5.yaml"
MODEL:
  WEIGHTS: "models/VGG/VGG_ILSVRC_16_layers_v1_d2.pkl" # download from https://github.com/shenyunhang/DRN-WSOD-pytorch
  MASK_ON: False
  VGG:
    DEPTH: 16
    CONV5_DILATION: 2
    OUT_FEATURES: ["plain2","plain5"]
  BACKBONE:
    NAME: "build_vgg_backbone"
    FREEZE_AT: 0
  ROI_HEADS:
    IN_FEATURES: ["plain5"]
    NUM_CLASSES: 20
  ROI_BOX_HEAD:
    FC_DIM: 4096
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
TEST:
  EVAL_PERIOD: 5000
DATASETS:
  TRAIN: ('clipart1k_traintest',)
  TRAIN_SOURCE: ('voc_2007_trainval', 'voc_2012_trainval')
  TEST: ('clipart1k_traintest',)
SOLVER:
  STEPS: (24000, 32000)
  MAX_ITER: 36000
  WARMUP_ITERS: 400
  IMS_PER_BATCH: 4 # image number for each domain
  BASE_LR: 0.0025 
OUTPUT_DIR: "./output"
DATALOADER:
  NUM_WORKERS: 4
