_BASE_: "../Base-RCNN-C4.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
    OUT_FEATURES: ["res2", "res4"]
  BACKBONE:
    FREEZE_AT: 0
  ROI_HEADS:
    NUM_CLASSES: 20
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
TEST:
  EVAL_PERIOD: 5000
DATASETS:
  TRAIN: ('clipart1k_traintest',)
  TRAIN_SOURCE: ('voc_2007_trainval', 'voc_2012_trainval')
  TEST: ('clipart1k_traintest',)
SOLVER:
  STEPS: (24000, 32000)
  MAX_ITER: 36000
  WARMUP_ITERS: 400
  IMS_PER_BATCH: 4 # image number for each domain
  BASE_LR: 0.005 
OUTPUT_DIR: "./output"
DATALOADER:
  NUM_WORKERS: 4
