_BASE_: [
    '../datasets/voc.yml',
    '../runtime.yml',
    '_base_/optimizer_1x.yml',
    '_base_/faster_rcnn_r50.yml',
    '_base_/faster_reader.yml',
]

pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/ResNet101_pretrained.pdparams
weights: output/faster_rcnn_r101_1x_voc/model_final

ResNet:
  # index 0 stands for res2
  depth: 101
  norm_type: bn
  freeze_at: 0
  return_idx: [2]
  num_stages: 3
